### PR TITLE
Changed popup window positioning calculations

### PR DESCRIPTION
**Pull request by godban**
Hello @ellisonleao,

Great job with gathering all this social share links.
I found that popup window positioning can be implemented in more clever way. It also can work with multiple screens instead of two.

Thank you

### CODE REVIEW

**Comment by ellisonleao** [comment]
Hey @godban thanks for the PR! the change is great, but will it work on IE 8< ? 

Probably the best way is changing the width and height check to something like

```
var w = window.innerWidth
|| document.documentElement.clientWidth
|| document.body.clientWidth;

var h = window.innerHeight
|| document.documentElement.clientHeight
|| document.body.clientHeight;
```

Let me know what you think!

**Comment by godban** [comment]
@ellisonleao no, ie9+ because of .innerWidth / Height

I didn't find any info about browser support in docs. Are you still supporting IE8-? And do you really need it? Support of it was shut down for a while, and currently it's hard to find that 0.3% users that still alive globally.

**Comment by ellisonleao** [comment]
Yeah, probably not worth burning nerurones on that. Let's merge it

**Comment by godban** [comment]
cool :ok_hand:

**Pull request merged**
