### PR TITLE
Updated Xing shareUrl and removed unsupported params

### PR DESCRIPTION
**Pull request by maximilianoertel**
First and foremost, thanks for building this little library! 

We've been using this on a couple of projects as a dependency via npm and noticed that the Xing sharing is currently broken. 

It appears that Xing changed the URL from `https://www.xing.com/app/user?op=share&url=` to `https://www.xing.com/social/share/spi?url=` and also removed the support for the `title` parameter. 

Took the liberty to open a pull request with the updated shareUrl – hope this is okay. 

Thanks!

### CODE REVIEW

**Review by ellisonleao — APPROVED** [review]

**Comment by ellisonleao** [comment]
thanks @maximilianoertel

**Comment by maximilianoertel** [comment]
@ellisonleao Thanks for merging and releasing 0.4.1 so quickly! Just to confirm, will the version be published on npm as well?

**Comment by ellisonleao** [comment]
@maximilianoertel i just did it

**Comment by maximilianoertel** [comment]
@ellisonleao Wonderful, thank you!

**Pull request merged**
