### PR TITLE
Fix: Sharer object pointing invalid construtor property

### PR DESCRIPTION
**Pull request by m-sureshraj**
Sharer object pointing invalid constructor property.

Sharer.prototype = {...};
will override the sharer obj default constructor (Sharer) property to (Object)

console.log(Sharer.constructor === Sharer); //false
console.log(Sharer.constructor === Object); //true

Manually set the constructor property
Sharer.prototype = {constructor: Sharer, ....}

console.log(Sharer.constructor === Sharer); //true

done..

### CODE REVIEW

**Comment by ellisonleao** [comment]
Can you remove the minification changes? i can do it myself.

**Comment by m-sureshraj** [comment]
Sorry... i didn't get that. Minification change mean...? Can u tell me more about that..

**Comment by ellisonleao** [comment]
there is a change on the `sharer.min.js` file . Can you please remove that change and just leave the `sharer.js` file change?

**Comment by m-sureshraj** [comment]
Yes sure..

**Comment by m-sureshraj** [comment]
Really sorry @ellisonleao, i couldn't remove the minification changes. Pls close this PR.
You can manually add this code " Sharer.prototype = {constructor: Sharer, ....} in to sharer.js file.
sorry for your inconvenience and time. Thank you.

**Pull request closed without merging**
