### PR TITLE
Facebook feed sharer, VK image support. Add uglifyjs as dev dependency

### PR DESCRIPTION
**Pull request by indieveed**
Add facebook sharer via feed dialog.
Add support for custom image in VK sharer
Add uglifyjs as dev dependency to package.json for build

### CODE REVIEW

**Comment by ellisonleao** [comment]
hey @indieveed , thanks for the PR! I have a few comments:

- Can you please remove https://github.com/indieveed/sharer.js/commit/973829fc9035cacb98a928f7d07f51f4fe91b1bd ? I don't believe we need the dialog feed since the fb sharer already shares on multiple fb places and its adding a lot of complexity (so many params).

i've just added a test.sh script to make a very basic test on travis. Can you move it to the `test` script too?  Also, can you remove the `compress.sh` script, since you moved it to package.json?

Thanks!

**Comment by indieveed** [comment]
@ellisonleao Unfortunately, feed dialog is the only way to share page with custom image set via JS (and not opengraph tags), and it is the case I am into on my current project. So I think it may be useful for other developers too.
Other comments seems legit

**Comment by ellisonleao** [comment]
@indieveed we can discuss that on another issue, what do you think? In the meantime, can we just merge the other remaining with the changes i've proposed? Let me know what you think!

**Comment by indieveed** [comment]
@ellisonleao OK, let's do like you say

**Comment by indieveed** [comment]
Rebased commits. Added issue #21.

**Comment by ellisonleao** [comment]
thanks @indieveed

**Pull request merged**
